use master
go
create database DB_TP2_Rubinstein
go
use DB_TP2_Rubinstein 
go

create table Marcas(
IdMarca int not null primary key identity (1,1),
Descripcion varchar (50) not null
)
go
create table Proveedores(
IdProveedor int not null primary key identity(1,1),
Nombre varchar (80) not null, 
)
go

create table Categorias(
IdCategoria int not null primary key identity (1,1),
Descripcion varchar (50) not null
)
go

create table Articulos(
IdArticulo int not null primary key identity(1,1),
Nombre varchar(60)not null,
Descripcion varchar(80) not null,
Marca int not null foreign key references Marcas(IdMarca),
Proveedor int not null foreign key references Proveedores(IdProveedor),
Categoria int not null foreign key references Categorias(IdCategoria),
Imagen varchar (150),
Precio decimal not null,
Estado bit not null
)
--create table ARTICULOS_X_CATEGORIAS(
--IdArticulo int not null foreign key references Articulos (IdArticulo),
--IdCategoria int not null foreign key references Categorias (IdCategoria)
--)
go

--MARCAS
INSERT INTO MARCAS (DESCRIPCION) VALUES ('PEPSI')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('OREO')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('7UP')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('DON SATUR')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('HERR KUKUMBER')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('ARCOR')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('FARGO')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('BIMBO')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('GALLO')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('TÍA MARUCA')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('BC')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('GEORGALOS')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('PHILIPS')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('PANASONIC')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('DOVE')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('ALA')
go

--PROVEEDORES
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PEPSICO')
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('PHILIPS SA')
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('UNILEVER')
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('GRUPO BIMBO')
INSERT INTO PROVEEDORES (NOMBRE) VALUES ('LA CAMPAGNOLA SACEI')
go

-- CATEGORIAS
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('GASEOSAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('PRODUCTOS LIGHT')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('GALLETITAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('CONSERVAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('ENCURTIDOS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('PAN LACTAL')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('MERMELADAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('SNACKS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('GOLOSINAS')
GO

--ARTICULOS
INSERT INTO ARTICULOS (NOMBRE,DESCRIPCION,MARCA,CATEGORIA,PROVEEDOR,IMAGEN,PRECIO,ESTADO) VALUES ('PASO DE LOS TOROS','BEBIDA SABOR POMELO',1,1,1,'https://geant.vteximg.com.br/arquivos/ids/205793-1000-1000/590789.jpg',45,1)
INSERT INTO ARTICULOS (NOMBRE,DESCRIPCION,MARCA,CATEGORIA,PROVEEDOR,IMAGEN,PRECIO,ESTADO) VALUES ('CHOCOARROZ','SNACK A BASE DE ARROZ',9,2,2,'https://jumboargentina.vteximg.com.br/arquivos/ids/454619-750-750/Alfajor-Chocoarroz-Dulce-De-Leche-X25g-1-254927.jpg?v=636596202506870000',20,1)
INSERT INTO ARTICULOS (NOMBRE,DESCRIPCION,MARCA,CATEGORIA,PROVEEDOR,IMAGEN,PRECIO,ESTADO) VALUES ('PAN ARTESANO','PAN ARTESANAL BIMBO',8,3,4,'https://www.superama.com.mx/Content/images/products/img_large/0750103046438L.jpg',30,0)

go

-- CATEGORIAS_X_ARTICULO
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (1, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (2, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (3, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (4, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (5, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (6, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (7, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (8, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (9, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (10, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (11, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (12, 1)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (4, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (5, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (6, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (10, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (11, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (12, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (13, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (14, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (15, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (16, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (28, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (29, 3)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (17, 4)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (34, 4)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (17, 5)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (34, 5)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (17, 8)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (34, 8)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (18, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (19, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (20, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (21, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (22, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (23, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (24, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (25, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (26, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (27, 6)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (30, 7)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (31, 7)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (31, 2)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (32, 8)
--INSERT INTO ARTICULOS_X_CATEGORIAS (IDARTICULO, IDCATEGORIA) VALUES (33, 9)

select * from marcas

Select art.IdArticulo, art.Nombre, art.Descripcion, M.Descripcion, Pro.Nombre,Cat.Descripcion, art.Imagen, art.Precio from ARTICULOS as art
INNER JOIN Marcas as M on art.Marca = M.IdMarca
INNER JOIN Proveedores as pro on art.Proveedor = pro.IdProveedor
INNER JOIN Categorias as cat on art.Categoria=cat.IdCategoria
where art.Estado=1

select * from articulos
